pipeline{
    agent{
        label 'AGENT-1'
    }
    options {
        ansiColor('xterm')
    }
    stages{
        stage('Init'){
            steps{
                withAWS(credentials: 'aws-creds', region: 'us-east-1'){
                 script{
                    sh """
                    cd 70-ingress-alb
                    terraform init --reconfigure
                    """
                  }
                }
               
            }
        }

        stage('Plan'){
            steps{
                withAWS(credentials: 'aws-creds', region: 'us-east-1'){
                 script{
                    sh """
                    cd 70-ingress-alb
                    terraform plan
                    """
                  }
                }
               
            }
        }

        stage('Apply'){
            steps{
                withAWS(credentials: 'aws-creds', region: 'us-east-1'){
                 script{
                    sh """
                    cd 70-ingress-alb
                    terraform apply -auto-approve
                    """
                  }
                }
               
            }
        }
    }
}