pipeline{
    agent{
        label 'AGENT-1'
    }
    options {
        ansiColor('xterm')
    }
    stages{
        stage('Init'){
            steps{
                withAWS(credentials: 'aws-creds', region: 'us-east-1'){
                    script{
                        sh """
                         cd 10-sg
                         terraform init --reconfigure
                        """
                    }

                }
               
            }
        }
        stage('Plan'){
            steps{
                withAWS(credentials: 'aws-creds', region: 'us-east-1'){
                    script{
                        sh """
                         cd 10-sg
                         terraform plan
                        """
                    }

                }
            }
        }
        stage('Apply'){
            steps{
                withAWS(credentials: 'aws-creds', region: 'us-east-1'){
                    script{
                        sh """
                         cd 10-sg
                         terraform apply -auto-approve
                        """
                    }

                }
            }
        }
        stage('Trigger Bastion,ACM,EKS'){
            parallel{
                stage('Trigger Bastion'){
                    steps{
                        script{
                            build job: '20-Bastion'
                            propagate: false
                            wait: false
                            
                        }
                    }
                }
                stage('Trigger ACM'){
                    steps{
                        script{
                            build job: '60-ACM'
                            propagate: false
                            wait: false
                            
                        }
                    }
                }
                stage('Trigger EKS'){
                    steps{
                        script{
                            build job: '80-eks'
                            propagate: false
                            wait: false
                            
                        }
                    }
                }

            }
           
        }
     stage('Trigger 70-ingress-alb'){
        steps{
            script{
                build job: '70-ingress-alb'
                propagate: false
                wait: false
            }
        }
        
    }



    }
}